### ISSUE TITLE
Peer to Peer Code review :: Danny, David, Elijah & MD

### ISSUE THREAD

**Issue by aceDavon** [barakadanny/capstone-project-1#9]
## Morning session peer-to-peer code review :writing_hand: 
You have done a great job so far in implementing the Required design, Making the template completely responsive, and setting in the right colors and spacing. In addition to the work done so far, here are some optional recommendations to consider: 

- [ ] The dark bar at the top of the template could have lesser spacing on the horizontal axis, this is to make the site appear more like a dynamic one than it is static,
- [ ] Your card section where you have the lectures and events, What do you think about making them take the full width of the screen right up from the tablet viewpoint? This is to ensure better readability as the font size keeps reducing as you scale down to the tablet region.
Weldone again for the great work done so far :clap:

**Comment by barakadanny** [comment]
@aceDavon Thank you for the Issue created
